package net.got.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.got.GotMod;

import java.util.function.Function;

public class GotModItems {
    public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(GotMod.MODID);
    public static final DeferredItem<Item> WEIRWOOD_LOG = block(GotModBlocks.WEIRWOOD_LOG);
    public static final DeferredItem<Item> WEIRWOOD_WOOD = block(GotModBlocks.WEIRWOOD_WOOD);
    public static final DeferredItem<Item> WEIRWOOD_PLANKS = block(GotModBlocks.WEIRWOOD_PLANKS);
    public static final DeferredItem<Item> WEIRWOOD_LEAVES = block(GotModBlocks.WEIRWOOD_LEAVES);
    public static final DeferredItem<Item> WEIRWOOD_STAIRS = block(GotModBlocks.WEIRWOOD_STAIRS);
    public static final DeferredItem<Item> WEIRWOOD_SLAB = block(GotModBlocks.WEIRWOOD_SLAB);
    public static final DeferredItem<Item> WEIRWOOD_FENCE = block(GotModBlocks.WEIRWOOD_FENCE);
    public static final DeferredItem<Item> WEIRWOOD_FENCE_GATE = block(GotModBlocks.WEIRWOOD_FENCE_GATE);
    public static final DeferredItem<Item> WEIRWOOD_PRESSURE_PLATE = block(GotModBlocks.WEIRWOOD_PRESSURE_PLATE);
    public static final DeferredItem<Item> WEIRWOOD_BUTTON = block(GotModBlocks.WEIRWOOD_BUTTON);
    public static final DeferredItem<Item> ASPEN_LOG = block(GotModBlocks.ASPEN_LOG);
    public static final DeferredItem<Item> ASPEN_WOOD = block(GotModBlocks.ASPEN_WOOD);
    public static final DeferredItem<Item> ASPEN_PLANKS = block(GotModBlocks.ASPEN_PLANKS);
    public static final DeferredItem<Item> ASPEN_LEAVES = block(GotModBlocks.ASPEN_LEAVES);
    public static final DeferredItem<Item> ASPEN_STAIRS = block(GotModBlocks.ASPEN_STAIRS);
    public static final DeferredItem<Item> ASPEN_SLAB = block(GotModBlocks.ASPEN_SLAB);
    public static final DeferredItem<Item> ASPEN_FENCE = block(GotModBlocks.ASPEN_FENCE);
    public static final DeferredItem<Item> ASPEN_FENCE_GATE = block(GotModBlocks.ASPEN_FENCE_GATE);
    public static final DeferredItem<Item> ASPEN_PRESSURE_PLATE = block(GotModBlocks.ASPEN_PRESSURE_PLATE);
    public static final DeferredItem<Item> ASPEN_BUTTON = block(GotModBlocks.ASPEN_BUTTON);
    public static final DeferredItem<Item> ALDER_LOG = block(GotModBlocks.ALDER_LOG);
    public static final DeferredItem<Item> ALDER_WOOD = block(GotModBlocks.ALDER_WOOD);
    public static final DeferredItem<Item> ALDER_PLANKS = block(GotModBlocks.ALDER_PLANKS);
    public static final DeferredItem<Item> ALDER_LEAVES = block(GotModBlocks.ALDER_LEAVES);
    public static final DeferredItem<Item> ALDER_STAIRS = block(GotModBlocks.ALDER_STAIRS);
    public static final DeferredItem<Item> ALDER_SLAB = block(GotModBlocks.ALDER_SLAB);
    public static final DeferredItem<Item> ALDER_FENCE = block(GotModBlocks.ALDER_FENCE);
    public static final DeferredItem<Item> ALDER_FENCE_GATE = block(GotModBlocks.ALDER_FENCE_GATE);
    public static final DeferredItem<Item> ALDER_PRESSURE_PLATE = block(GotModBlocks.ALDER_PRESSURE_PLATE);
    public static final DeferredItem<Item> ALDER_BUTTON = block(GotModBlocks.ALDER_BUTTON);
	public static final DeferredItem<Item> PINE_LOG = block(GotModBlocks.PINE_LOG);
	public static final DeferredItem<Item> PINE_WOOD = block(GotModBlocks.PINE_WOOD);
	public static final DeferredItem<Item> PINE_PLANKS = block(GotModBlocks.PINE_PLANKS);
	public static final DeferredItem<Item> PINE_LEAVES = block(GotModBlocks.PINE_LEAVES);
	public static final DeferredItem<Item> PINE_STAIRS = block(GotModBlocks.PINE_STAIRS);
    public static final DeferredItem<Item> PINE_SLAB = block(GotModBlocks.PINE_SLAB);
	public static final DeferredItem<Item> PINE_FENCE = block(GotModBlocks.PINE_FENCE);
	public static final DeferredItem<Item> PINE_FENCE_GATE = block(GotModBlocks.PINE_FENCE_GATE);
	public static final DeferredItem<Item> PINE_PRESSURE_PLATE = block(GotModBlocks.PINE_PRESSURE_PLATE);
	public static final DeferredItem<Item> PINE_BUTTON = block(GotModBlocks.PINE_BUTTON);
	public static final DeferredItem<Item> FIR_LOG = block(GotModBlocks.FIR_LOG);
	public static final DeferredItem<Item> FIR_WOOD = block(GotModBlocks.FIR_WOOD);
	public static final DeferredItem<Item> FIR_PLANKS = block(GotModBlocks.FIR_PLANKS);
	public static final DeferredItem<Item> FIR_LEAVES = block(GotModBlocks.FIR_LEAVES);
	public static final DeferredItem<Item> FIR_STAIRS = block(GotModBlocks.FIR_STAIRS);
	public static final DeferredItem<Item> FIR_SLAB = block(GotModBlocks.FIR_SLAB);
	public static final DeferredItem<Item> FIR_FENCE = block(GotModBlocks.FIR_FENCE);
	public static final DeferredItem<Item> FIR_FENCE_GATE = block(GotModBlocks.FIR_FENCE_GATE);
	public static final DeferredItem<Item> FIR_PRESSURE_PLATE = block(GotModBlocks.FIR_PRESSURE_PLATE);
	public static final DeferredItem<Item> FIR_BUTTON = block(GotModBlocks.FIR_BUTTON);
	public static final DeferredItem<Item> SENTINAL_LOG = block(GotModBlocks.SENTINAL_LOG);
	public static final DeferredItem<Item> SENTINAL_WOOD = block(GotModBlocks.SENTINAL_WOOD);
	public static final DeferredItem<Item> SENTINAL_PLANKS = block(GotModBlocks.SENTINAL_PLANKS);
	public static final DeferredItem<Item> SENTINAL_LEAVES = block(GotModBlocks.SENTINAL_LEAVES);
	public static final DeferredItem<Item> SENTINAL_STAIRS = block(GotModBlocks.SENTINAL_STAIRS);
	public static final DeferredItem<Item> SENTINAL_SLAB = block(GotModBlocks.SENTINAL_SLAB);
	public static final DeferredItem<Item> SENTINAL_FENCE = block(GotModBlocks.SENTINAL_FENCE);
	public static final DeferredItem<Item> SENTINAL_FENCE_GATE = block(GotModBlocks.SENTINAL_FENCE_GATE);
	public static final DeferredItem<Item> SENTINAL_PRESSURE_PLATE = block(GotModBlocks.SENTINAL_PRESSURE_PLATE);
	public static final DeferredItem<Item> SENTINAL_BUTTON = block(GotModBlocks.SENTINAL_BUTTON);
	public static final DeferredItem<Item> IRONWOOD_LOG = block(GotModBlocks.IRONWOOD_LOG);
	public static final DeferredItem<Item> IRONWOOD_WOOD = block(GotModBlocks.IRONWOOD_WOOD);
	public static final DeferredItem<Item> IRONWOOD_PLANKS = block(GotModBlocks.IRONWOOD_PLANKS);
	public static final DeferredItem<Item> IRONWOOD_LEAVES = block(GotModBlocks.IRONWOOD_LEAVES);
	public static final DeferredItem<Item> IRONWOOD_STAIRS = block(GotModBlocks.IRONWOOD_STAIRS);
	public static final DeferredItem<Item> IRONWOOD_SLAB = block(GotModBlocks.IRONWOOD_SLAB);
	public static final DeferredItem<Item> IRONWOOD_FENCE = block(GotModBlocks.IRONWOOD_FENCE);
	public static final DeferredItem<Item> IRONWOOD_FENCE_GATE = block(GotModBlocks.IRONWOOD_FENCE_GATE);
	public static final DeferredItem<Item> IRONWOOD_PRESSURE_PLATE = block(GotModBlocks.IRONWOOD_PRESSURE_PLATE);
	public static final DeferredItem<Item> IRONWOOD_BUTTON = block(GotModBlocks.IRONWOOD_BUTTON);
    public static final DeferredItem<Item> BEECH_LOG = block(GotModBlocks.BEECH_LOG);
	public static final DeferredItem<Item> BEECH_WOOD = block(GotModBlocks.BEECH_WOOD);
	public static final DeferredItem<Item> BEECH_PLANKS = block(GotModBlocks.BEECH_PLANKS);
	public static final DeferredItem<Item> BEECH_LEAVES = block(GotModBlocks.BEECH_LEAVES);
	public static final DeferredItem<Item> BEECH_STAIRS = block(GotModBlocks.BEECH_STAIRS);
	public static final DeferredItem<Item> BEECH_SLAB = block(GotModBlocks.BEECH_SLAB);
	public static final DeferredItem<Item> BEECH_FENCE = block(GotModBlocks.BEECH_FENCE);
	public static final DeferredItem<Item> BEECH_FENCE_GATE = block(GotModBlocks.BEECH_FENCE_GATE);
	public static final DeferredItem<Item> BEECH_PRESSURE_PLATE = block(GotModBlocks.BEECH_PRESSURE_PLATE);
	public static final DeferredItem<Item> BEECH_BUTTON = block(GotModBlocks.BEECH_BUTTON);
	public static final DeferredItem<Item> SOLDIER_PINE_LOG = block(GotModBlocks.SOLDIER_PINE_LOG);
	public static final DeferredItem<Item> SOLDIER_PINE_WOOD = block(GotModBlocks.SOLDIER_PINE_WOOD);
	public static final DeferredItem<Item> SOLDIER_PINE_PLANKS = block(GotModBlocks.SOLDIER_PINE_PLANKS);
	public static final DeferredItem<Item> SOLDIER_PINE_LEAVES = block(GotModBlocks.SOLDIER_PINE_LEAVES);
	public static final DeferredItem<Item> SOLDIER_PINE_STAIRS = block(GotModBlocks.SOLDIER_PINE_STAIRS);
	public static final DeferredItem<Item> SOLDIER_PINE_SLAB = block(GotModBlocks.SOLDIER_PINE_SLAB);
	public static final DeferredItem<Item> SOLDIER_PINE_FENCE = block(GotModBlocks.SOLDIER_PINE_FENCE);
	public static final DeferredItem<Item> SOLDIER_PINE_FENCE_GATE = block(GotModBlocks.SOLDIER_PINE_FENCE_GATE);
	public static final DeferredItem<Item> SOLDIER_PINE_PRESSURE_PLATE = block(GotModBlocks.SOLDIER_PINE_PRESSURE_PLATE);
	public static final DeferredItem<Item> SOLDIER_PINE_BUTTON = block(GotModBlocks.SOLDIER_PINE_BUTTON);
    public static final DeferredItem<Item> ASH_LOG = block(GotModBlocks.ASH_LOG);
    public static final DeferredItem<Item> ASH_WOOD = block(GotModBlocks.ASH_WOOD);
    public static final DeferredItem<Item> ASH_PLANKS = block(GotModBlocks.ASH_PLANKS);
    public static final DeferredItem<Item> ASH_LEAVES = block(GotModBlocks.ASH_LEAVES);
    public static final DeferredItem<Item> ASH_STAIRS = block(GotModBlocks.ASH_STAIRS);
    public static final DeferredItem<Item> ASH_SLAB = block(GotModBlocks.ASH_SLAB);
    public static final DeferredItem<Item> ASH_FENCE = block(GotModBlocks.ASH_FENCE);
    public static final DeferredItem<Item> ASH_FENCE_GATE = block(GotModBlocks.ASH_FENCE_GATE);
    public static final DeferredItem<Item> ASH_PRESSURE_PLATE = block(GotModBlocks.ASH_PRESSURE_PLATE);
    public static final DeferredItem<Item> ASH_BUTTON = block(GotModBlocks.ASH_BUTTON);
    public static final DeferredItem<Item> HAWTHORN_LOG = block(GotModBlocks.HAWTHORN_LOG);
    public static final DeferredItem<Item> HAWTHORN_WOOD = block(GotModBlocks.HAWTHORN_WOOD);
    public static final DeferredItem<Item> HAWTHORN_PLANKS = block(GotModBlocks.HAWTHORN_PLANKS);
    public static final DeferredItem<Item> HAWTHORN_LEAVES = block(GotModBlocks.HAWTHORN_LEAVES);
    public static final DeferredItem<Item> HAWTHORN_STAIRS = block(GotModBlocks.HAWTHORN_STAIRS);
    public static final DeferredItem<Item> HAWTHORN_SLAB = block(GotModBlocks.HAWTHORN_SLAB);
    public static final DeferredItem<Item> HAWTHORN_FENCE = block(GotModBlocks.HAWTHORN_FENCE);
    public static final DeferredItem<Item> HAWTHORN_FENCE_GATE = block(GotModBlocks.HAWTHORN_FENCE_GATE);
    public static final DeferredItem<Item> HAWTHORN_PRESSURE_PLATE = block(GotModBlocks.HAWTHORN_PRESSURE_PLATE);
    public static final DeferredItem<Item> HAWTHORN_BUTTON = block(GotModBlocks.HAWTHORN_BUTTON);

    // ── Crownlands ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> CROWNLANDS_ROCK = block(GotModBlocks.CROWNLANDS_ROCK);
    public static final DeferredItem<Item> CROWNLANDS_BRICK = block(GotModBlocks.CROWNLANDS_BRICK);
    public static final DeferredItem<Item> CRACKED_CROWNLANDS_BRICK = block(GotModBlocks.CRACKED_CROWNLANDS_BRICK);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_BRICK = block(GotModBlocks.MOSSY_CROWNLANDS_BRICK);
    public static final DeferredItem<Item> CROWNLANDS_COBBLESTONE = block(GotModBlocks.CROWNLANDS_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_COBBLESTONE = block(GotModBlocks.MOSSY_CROWNLANDS_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_CROWNLANDS_ROCK = block(GotModBlocks.POLISHED_CROWNLANDS_ROCK);
    public static final DeferredItem<Item> CROWNLANDS_PILLAR = block(GotModBlocks.CROWNLANDS_PILLAR);

    // ── Dorne ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> DORNE_ROCK = block(GotModBlocks.DORNE_ROCK);
    public static final DeferredItem<Item> DORNE_BRICK = block(GotModBlocks.DORNE_BRICK);
    public static final DeferredItem<Item> CRACKED_DORNE_BRICK = block(GotModBlocks.CRACKED_DORNE_BRICK);
    public static final DeferredItem<Item> MOSSY_DORNE_BRICK = block(GotModBlocks.MOSSY_DORNE_BRICK);
    public static final DeferredItem<Item> DORNE_COBBLESTONE = block(GotModBlocks.DORNE_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_DORNE_COBBLESTONE = block(GotModBlocks.MOSSY_DORNE_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_DORNE_ROCK = block(GotModBlocks.POLISHED_DORNE_ROCK);
    public static final DeferredItem<Item> DORNE_PILLAR = block(GotModBlocks.DORNE_PILLAR);

    // ── Iron Islands ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> IRON_ISLANDS_ROCK = block(GotModBlocks.IRON_ISLANDS_ROCK);
    public static final DeferredItem<Item> IRON_ISLANDS_BRICK = block(GotModBlocks.IRON_ISLANDS_BRICK);
    public static final DeferredItem<Item> CRACKED_IRON_ISLANDS_BRICK = block(GotModBlocks.CRACKED_IRON_ISLANDS_BRICK);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_BRICK = block(GotModBlocks.MOSSY_IRON_ISLANDS_BRICK);
    public static final DeferredItem<Item> IRON_ISLANDS_COBBLESTONE = block(GotModBlocks.IRON_ISLANDS_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_COBBLESTONE = block(GotModBlocks.MOSSY_IRON_ISLANDS_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_IRON_ISLANDS_ROCK = block(GotModBlocks.POLISHED_IRON_ISLANDS_ROCK);
    public static final DeferredItem<Item> IRON_ISLANDS_PILLAR = block(GotModBlocks.IRON_ISLANDS_PILLAR);

    // ── North ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> NORTH_ROCK = block(GotModBlocks.NORTH_ROCK);
    public static final DeferredItem<Item> NORTH_BRICK = block(GotModBlocks.NORTH_BRICK);
    public static final DeferredItem<Item> CRACKED_NORTH_BRICK = block(GotModBlocks.CRACKED_NORTH_BRICK);
    public static final DeferredItem<Item> MOSSY_NORTH_BRICK = block(GotModBlocks.MOSSY_NORTH_BRICK);
    public static final DeferredItem<Item> NORTH_COBBLESTONE = block(GotModBlocks.NORTH_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_NORTH_COBBLESTONE = block(GotModBlocks.MOSSY_NORTH_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_NORTH_ROCK = block(GotModBlocks.POLISHED_NORTH_ROCK);
    public static final DeferredItem<Item> NORTH_PILLAR = block(GotModBlocks.NORTH_PILLAR);

    // ── Reach ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> REACH_ROCK = block(GotModBlocks.REACH_ROCK);
    public static final DeferredItem<Item> REACH_BRICK = block(GotModBlocks.REACH_BRICK);
    public static final DeferredItem<Item> CRACKED_REACH_BRICK = block(GotModBlocks.CRACKED_REACH_BRICK);
    public static final DeferredItem<Item> MOSSY_REACH_BRICK = block(GotModBlocks.MOSSY_REACH_BRICK);
    public static final DeferredItem<Item> REACH_COBBLESTONE = block(GotModBlocks.REACH_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_REACH_COBBLESTONE = block(GotModBlocks.MOSSY_REACH_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_REACH_ROCK = block(GotModBlocks.POLISHED_REACH_ROCK);
    public static final DeferredItem<Item> REACH_PILLAR = block(GotModBlocks.REACH_PILLAR);

    // ── Riverlands ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> RIVERLANDS_ROCK = block(GotModBlocks.RIVERLANDS_ROCK);
    public static final DeferredItem<Item> RIVERLANDS_BRICK = block(GotModBlocks.RIVERLANDS_BRICK);
    public static final DeferredItem<Item> CRACKED_RIVERLANDS_BRICK = block(GotModBlocks.CRACKED_RIVERLANDS_BRICK);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_BRICK = block(GotModBlocks.MOSSY_RIVERLANDS_BRICK);
    public static final DeferredItem<Item> RIVERLANDS_COBBLESTONE = block(GotModBlocks.RIVERLANDS_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_COBBLESTONE = block(GotModBlocks.MOSSY_RIVERLANDS_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_RIVERLANDS_ROCK = block(GotModBlocks.POLISHED_RIVERLANDS_ROCK);
    public static final DeferredItem<Item> RIVERLANDS_PILLAR = block(GotModBlocks.RIVERLANDS_PILLAR);

    // ── Stormlands ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> STORMLANDS_ROCK = block(GotModBlocks.STORMLANDS_ROCK);
    public static final DeferredItem<Item> STORMLANDS_BRICK = block(GotModBlocks.STORMLANDS_BRICK);
    public static final DeferredItem<Item> CRACKED_STORMLANDS_BRICK = block(GotModBlocks.CRACKED_STORMLANDS_BRICK);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_BRICK = block(GotModBlocks.MOSSY_STORMLANDS_BRICK);
    public static final DeferredItem<Item> STORMLANDS_COBBLESTONE = block(GotModBlocks.STORMLANDS_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_COBBLESTONE = block(GotModBlocks.MOSSY_STORMLANDS_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_STORMLANDS_ROCK = block(GotModBlocks.POLISHED_STORMLANDS_ROCK);
    public static final DeferredItem<Item> STORMLANDS_PILLAR = block(GotModBlocks.STORMLANDS_PILLAR);

    // ── Vale ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> VALE_ROCK = block(GotModBlocks.VALE_ROCK);
    public static final DeferredItem<Item> VALE_BRICK = block(GotModBlocks.VALE_BRICK);
    public static final DeferredItem<Item> CRACKED_VALE_BRICK = block(GotModBlocks.CRACKED_VALE_BRICK);
    public static final DeferredItem<Item> MOSSY_VALE_BRICK = block(GotModBlocks.MOSSY_VALE_BRICK);
    public static final DeferredItem<Item> VALE_COBBLESTONE = block(GotModBlocks.VALE_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_VALE_COBBLESTONE = block(GotModBlocks.MOSSY_VALE_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_VALE_ROCK = block(GotModBlocks.POLISHED_VALE_ROCK);
    public static final DeferredItem<Item> VALE_PILLAR = block(GotModBlocks.VALE_PILLAR);

    // ── Westerlands ──────────────────────────────────────────────────────
    public static final DeferredItem<Item> WESTERLANDS_ROCK = block(GotModBlocks.WESTERLANDS_ROCK);
    public static final DeferredItem<Item> WESTERLANDS_BRICK = block(GotModBlocks.WESTERLANDS_BRICK);
    public static final DeferredItem<Item> CRACKED_WESTERLANDS_BRICK = block(GotModBlocks.CRACKED_WESTERLANDS_BRICK);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_BRICK = block(GotModBlocks.MOSSY_WESTERLANDS_BRICK);
    public static final DeferredItem<Item> WESTERLANDS_COBBLESTONE = block(GotModBlocks.WESTERLANDS_COBBLESTONE);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_COBBLESTONE = block(GotModBlocks.MOSSY_WESTERLANDS_COBBLESTONE);
    public static final DeferredItem<Item> POLISHED_WESTERLANDS_ROCK = block(GotModBlocks.POLISHED_WESTERLANDS_ROCK);
    public static final DeferredItem<Item> WESTERLANDS_PILLAR = block(GotModBlocks.WESTERLANDS_PILLAR);

    // ── Crownlands ─────────────────────────────────────────
    public static final DeferredItem<Item> CROWNLANDS_ROCK_SLAB = block(GotModBlocks.CROWNLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> CROWNLANDS_ROCK_STAIRS = block(GotModBlocks.CROWNLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> CROWNLANDS_ROCK_WALL = block(GotModBlocks.CROWNLANDS_ROCK_WALL);
    public static final DeferredItem<Item> CROWNLANDS_ROCK_BUTTON = block(GotModBlocks.CROWNLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> CROWNLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.CROWNLANDS_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CROWNLANDS_BRICK_SLAB = block(GotModBlocks.CROWNLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> CROWNLANDS_BRICK_STAIRS = block(GotModBlocks.CROWNLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> CROWNLANDS_BRICK_WALL = block(GotModBlocks.CROWNLANDS_BRICK_WALL);
    public static final DeferredItem<Item> CROWNLANDS_BRICK_BUTTON = block(GotModBlocks.CROWNLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> CROWNLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.CROWNLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_CROWNLANDS_BRICK_SLAB = block(GotModBlocks.CRACKED_CROWNLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_CROWNLANDS_BRICK_STAIRS = block(GotModBlocks.CRACKED_CROWNLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_CROWNLANDS_BRICK_WALL = block(GotModBlocks.CRACKED_CROWNLANDS_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_CROWNLANDS_BRICK_BUTTON = block(GotModBlocks.CRACKED_CROWNLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_CROWNLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_CROWNLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_BRICK_SLAB = block(GotModBlocks.MOSSY_CROWNLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_BRICK_STAIRS = block(GotModBlocks.MOSSY_CROWNLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_BRICK_WALL = block(GotModBlocks.MOSSY_CROWNLANDS_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_BRICK_BUTTON = block(GotModBlocks.MOSSY_CROWNLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_CROWNLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CROWNLANDS_COBBLESTONE_SLAB = block(GotModBlocks.CROWNLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> CROWNLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.CROWNLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> CROWNLANDS_COBBLESTONE_WALL = block(GotModBlocks.CROWNLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> CROWNLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.CROWNLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> CROWNLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.CROWNLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_CROWNLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_CROWNLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_CROWNLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_CROWNLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_CROWNLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_CROWNLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_CROWNLANDS_ROCK_SLAB = block(GotModBlocks.POLISHED_CROWNLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_CROWNLANDS_ROCK_STAIRS = block(GotModBlocks.POLISHED_CROWNLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_CROWNLANDS_ROCK_WALL = block(GotModBlocks.POLISHED_CROWNLANDS_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_CROWNLANDS_ROCK_BUTTON = block(GotModBlocks.POLISHED_CROWNLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_CROWNLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_CROWNLANDS_ROCK_PRESSURE_PLATE);

    // ── Dorne ─────────────────────────────────────────
    public static final DeferredItem<Item> DORNE_ROCK_SLAB = block(GotModBlocks.DORNE_ROCK_SLAB);
    public static final DeferredItem<Item> DORNE_ROCK_STAIRS = block(GotModBlocks.DORNE_ROCK_STAIRS);
    public static final DeferredItem<Item> DORNE_ROCK_WALL = block(GotModBlocks.DORNE_ROCK_WALL);
    public static final DeferredItem<Item> DORNE_ROCK_BUTTON = block(GotModBlocks.DORNE_ROCK_BUTTON);
    public static final DeferredItem<Item> DORNE_ROCK_PRESSURE_PLATE = block(GotModBlocks.DORNE_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> DORNE_BRICK_SLAB = block(GotModBlocks.DORNE_BRICK_SLAB);
    public static final DeferredItem<Item> DORNE_BRICK_STAIRS = block(GotModBlocks.DORNE_BRICK_STAIRS);
    public static final DeferredItem<Item> DORNE_BRICK_WALL = block(GotModBlocks.DORNE_BRICK_WALL);
    public static final DeferredItem<Item> DORNE_BRICK_BUTTON = block(GotModBlocks.DORNE_BRICK_BUTTON);
    public static final DeferredItem<Item> DORNE_BRICK_PRESSURE_PLATE = block(GotModBlocks.DORNE_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_DORNE_BRICK_SLAB = block(GotModBlocks.CRACKED_DORNE_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_DORNE_BRICK_STAIRS = block(GotModBlocks.CRACKED_DORNE_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_DORNE_BRICK_WALL = block(GotModBlocks.CRACKED_DORNE_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_DORNE_BRICK_BUTTON = block(GotModBlocks.CRACKED_DORNE_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_DORNE_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_DORNE_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_DORNE_BRICK_SLAB = block(GotModBlocks.MOSSY_DORNE_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_DORNE_BRICK_STAIRS = block(GotModBlocks.MOSSY_DORNE_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_DORNE_BRICK_WALL = block(GotModBlocks.MOSSY_DORNE_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_DORNE_BRICK_BUTTON = block(GotModBlocks.MOSSY_DORNE_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_DORNE_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_DORNE_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> DORNE_COBBLESTONE_SLAB = block(GotModBlocks.DORNE_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> DORNE_COBBLESTONE_STAIRS = block(GotModBlocks.DORNE_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> DORNE_COBBLESTONE_WALL = block(GotModBlocks.DORNE_COBBLESTONE_WALL);
    public static final DeferredItem<Item> DORNE_COBBLESTONE_BUTTON = block(GotModBlocks.DORNE_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> DORNE_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.DORNE_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_DORNE_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_DORNE_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_DORNE_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_DORNE_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_DORNE_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_DORNE_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_DORNE_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_DORNE_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_DORNE_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_DORNE_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_DORNE_ROCK_SLAB = block(GotModBlocks.POLISHED_DORNE_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_DORNE_ROCK_STAIRS = block(GotModBlocks.POLISHED_DORNE_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_DORNE_ROCK_WALL = block(GotModBlocks.POLISHED_DORNE_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_DORNE_ROCK_BUTTON = block(GotModBlocks.POLISHED_DORNE_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_DORNE_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_DORNE_ROCK_PRESSURE_PLATE);

    // ── Iron Islands ─────────────────────────────────────────
    public static final DeferredItem<Item> IRON_ISLANDS_ROCK_SLAB = block(GotModBlocks.IRON_ISLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> IRON_ISLANDS_ROCK_STAIRS = block(GotModBlocks.IRON_ISLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> IRON_ISLANDS_ROCK_WALL = block(GotModBlocks.IRON_ISLANDS_ROCK_WALL);
    public static final DeferredItem<Item> IRON_ISLANDS_ROCK_BUTTON = block(GotModBlocks.IRON_ISLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> IRON_ISLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.IRON_ISLANDS_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> IRON_ISLANDS_BRICK_SLAB = block(GotModBlocks.IRON_ISLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> IRON_ISLANDS_BRICK_STAIRS = block(GotModBlocks.IRON_ISLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> IRON_ISLANDS_BRICK_WALL = block(GotModBlocks.IRON_ISLANDS_BRICK_WALL);
    public static final DeferredItem<Item> IRON_ISLANDS_BRICK_BUTTON = block(GotModBlocks.IRON_ISLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> IRON_ISLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.IRON_ISLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_IRON_ISLANDS_BRICK_SLAB = block(GotModBlocks.CRACKED_IRON_ISLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_IRON_ISLANDS_BRICK_STAIRS = block(GotModBlocks.CRACKED_IRON_ISLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_IRON_ISLANDS_BRICK_WALL = block(GotModBlocks.CRACKED_IRON_ISLANDS_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_IRON_ISLANDS_BRICK_BUTTON = block(GotModBlocks.CRACKED_IRON_ISLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_IRON_ISLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_IRON_ISLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_BRICK_SLAB = block(GotModBlocks.MOSSY_IRON_ISLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_BRICK_STAIRS = block(GotModBlocks.MOSSY_IRON_ISLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_BRICK_WALL = block(GotModBlocks.MOSSY_IRON_ISLANDS_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_BRICK_BUTTON = block(GotModBlocks.MOSSY_IRON_ISLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_IRON_ISLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> IRON_ISLANDS_COBBLESTONE_SLAB = block(GotModBlocks.IRON_ISLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> IRON_ISLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.IRON_ISLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> IRON_ISLANDS_COBBLESTONE_WALL = block(GotModBlocks.IRON_ISLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> IRON_ISLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.IRON_ISLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> IRON_ISLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.IRON_ISLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_IRON_ISLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_IRON_ISLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_IRON_ISLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_IRON_ISLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_IRON_ISLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_IRON_ISLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_IRON_ISLANDS_ROCK_SLAB = block(GotModBlocks.POLISHED_IRON_ISLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_IRON_ISLANDS_ROCK_STAIRS = block(GotModBlocks.POLISHED_IRON_ISLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_IRON_ISLANDS_ROCK_WALL = block(GotModBlocks.POLISHED_IRON_ISLANDS_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_IRON_ISLANDS_ROCK_BUTTON = block(GotModBlocks.POLISHED_IRON_ISLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_IRON_ISLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_IRON_ISLANDS_ROCK_PRESSURE_PLATE);

    // ── North ─────────────────────────────────────────
    public static final DeferredItem<Item> NORTH_ROCK_SLAB = block(GotModBlocks.NORTH_ROCK_SLAB);
    public static final DeferredItem<Item> NORTH_ROCK_STAIRS = block(GotModBlocks.NORTH_ROCK_STAIRS);
    public static final DeferredItem<Item> NORTH_ROCK_WALL = block(GotModBlocks.NORTH_ROCK_WALL);
    public static final DeferredItem<Item> NORTH_ROCK_BUTTON = block(GotModBlocks.NORTH_ROCK_BUTTON);
    public static final DeferredItem<Item> NORTH_ROCK_PRESSURE_PLATE = block(GotModBlocks.NORTH_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> NORTH_BRICK_SLAB = block(GotModBlocks.NORTH_BRICK_SLAB);
    public static final DeferredItem<Item> NORTH_BRICK_STAIRS = block(GotModBlocks.NORTH_BRICK_STAIRS);
    public static final DeferredItem<Item> NORTH_BRICK_WALL = block(GotModBlocks.NORTH_BRICK_WALL);
    public static final DeferredItem<Item> NORTH_BRICK_BUTTON = block(GotModBlocks.NORTH_BRICK_BUTTON);
    public static final DeferredItem<Item> NORTH_BRICK_PRESSURE_PLATE = block(GotModBlocks.NORTH_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_NORTH_BRICK_SLAB = block(GotModBlocks.CRACKED_NORTH_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_NORTH_BRICK_STAIRS = block(GotModBlocks.CRACKED_NORTH_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_NORTH_BRICK_WALL = block(GotModBlocks.CRACKED_NORTH_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_NORTH_BRICK_BUTTON = block(GotModBlocks.CRACKED_NORTH_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_NORTH_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_NORTH_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_NORTH_BRICK_SLAB = block(GotModBlocks.MOSSY_NORTH_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_NORTH_BRICK_STAIRS = block(GotModBlocks.MOSSY_NORTH_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_NORTH_BRICK_WALL = block(GotModBlocks.MOSSY_NORTH_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_NORTH_BRICK_BUTTON = block(GotModBlocks.MOSSY_NORTH_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_NORTH_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_NORTH_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> NORTH_COBBLESTONE_SLAB = block(GotModBlocks.NORTH_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> NORTH_COBBLESTONE_STAIRS = block(GotModBlocks.NORTH_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> NORTH_COBBLESTONE_WALL = block(GotModBlocks.NORTH_COBBLESTONE_WALL);
    public static final DeferredItem<Item> NORTH_COBBLESTONE_BUTTON = block(GotModBlocks.NORTH_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> NORTH_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.NORTH_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_NORTH_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_NORTH_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_NORTH_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_NORTH_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_NORTH_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_NORTH_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_NORTH_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_NORTH_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_NORTH_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_NORTH_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_NORTH_ROCK_SLAB = block(GotModBlocks.POLISHED_NORTH_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_NORTH_ROCK_STAIRS = block(GotModBlocks.POLISHED_NORTH_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_NORTH_ROCK_WALL = block(GotModBlocks.POLISHED_NORTH_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_NORTH_ROCK_BUTTON = block(GotModBlocks.POLISHED_NORTH_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_NORTH_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_NORTH_ROCK_PRESSURE_PLATE);

    // ── Reach ─────────────────────────────────────────
    public static final DeferredItem<Item> REACH_ROCK_SLAB = block(GotModBlocks.REACH_ROCK_SLAB);
    public static final DeferredItem<Item> REACH_ROCK_STAIRS = block(GotModBlocks.REACH_ROCK_STAIRS);
    public static final DeferredItem<Item> REACH_ROCK_WALL = block(GotModBlocks.REACH_ROCK_WALL);
    public static final DeferredItem<Item> REACH_ROCK_BUTTON = block(GotModBlocks.REACH_ROCK_BUTTON);
    public static final DeferredItem<Item> REACH_ROCK_PRESSURE_PLATE = block(GotModBlocks.REACH_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> REACH_BRICK_SLAB = block(GotModBlocks.REACH_BRICK_SLAB);
    public static final DeferredItem<Item> REACH_BRICK_STAIRS = block(GotModBlocks.REACH_BRICK_STAIRS);
    public static final DeferredItem<Item> REACH_BRICK_WALL = block(GotModBlocks.REACH_BRICK_WALL);
    public static final DeferredItem<Item> REACH_BRICK_BUTTON = block(GotModBlocks.REACH_BRICK_BUTTON);
    public static final DeferredItem<Item> REACH_BRICK_PRESSURE_PLATE = block(GotModBlocks.REACH_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_REACH_BRICK_SLAB = block(GotModBlocks.CRACKED_REACH_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_REACH_BRICK_STAIRS = block(GotModBlocks.CRACKED_REACH_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_REACH_BRICK_WALL = block(GotModBlocks.CRACKED_REACH_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_REACH_BRICK_BUTTON = block(GotModBlocks.CRACKED_REACH_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_REACH_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_REACH_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_REACH_BRICK_SLAB = block(GotModBlocks.MOSSY_REACH_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_REACH_BRICK_STAIRS = block(GotModBlocks.MOSSY_REACH_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_REACH_BRICK_WALL = block(GotModBlocks.MOSSY_REACH_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_REACH_BRICK_BUTTON = block(GotModBlocks.MOSSY_REACH_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_REACH_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_REACH_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> REACH_COBBLESTONE_SLAB = block(GotModBlocks.REACH_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> REACH_COBBLESTONE_STAIRS = block(GotModBlocks.REACH_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> REACH_COBBLESTONE_WALL = block(GotModBlocks.REACH_COBBLESTONE_WALL);
    public static final DeferredItem<Item> REACH_COBBLESTONE_BUTTON = block(GotModBlocks.REACH_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> REACH_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.REACH_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_REACH_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_REACH_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_REACH_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_REACH_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_REACH_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_REACH_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_REACH_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_REACH_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_REACH_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_REACH_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_REACH_ROCK_SLAB = block(GotModBlocks.POLISHED_REACH_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_REACH_ROCK_STAIRS = block(GotModBlocks.POLISHED_REACH_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_REACH_ROCK_WALL = block(GotModBlocks.POLISHED_REACH_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_REACH_ROCK_BUTTON = block(GotModBlocks.POLISHED_REACH_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_REACH_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_REACH_ROCK_PRESSURE_PLATE);

    // ── Riverlands ─────────────────────────────────────────
    public static final DeferredItem<Item> RIVERLANDS_ROCK_SLAB = block(GotModBlocks.RIVERLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> RIVERLANDS_ROCK_STAIRS = block(GotModBlocks.RIVERLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> RIVERLANDS_ROCK_WALL = block(GotModBlocks.RIVERLANDS_ROCK_WALL);
    public static final DeferredItem<Item> RIVERLANDS_ROCK_BUTTON = block(GotModBlocks.RIVERLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> RIVERLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.RIVERLANDS_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> RIVERLANDS_BRICK_SLAB = block(GotModBlocks.RIVERLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> RIVERLANDS_BRICK_STAIRS = block(GotModBlocks.RIVERLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> RIVERLANDS_BRICK_WALL = block(GotModBlocks.RIVERLANDS_BRICK_WALL);
    public static final DeferredItem<Item> RIVERLANDS_BRICK_BUTTON = block(GotModBlocks.RIVERLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> RIVERLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.RIVERLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_RIVERLANDS_BRICK_SLAB = block(GotModBlocks.CRACKED_RIVERLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_RIVERLANDS_BRICK_STAIRS = block(GotModBlocks.CRACKED_RIVERLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_RIVERLANDS_BRICK_WALL = block(GotModBlocks.CRACKED_RIVERLANDS_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_RIVERLANDS_BRICK_BUTTON = block(GotModBlocks.CRACKED_RIVERLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_RIVERLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_RIVERLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_BRICK_SLAB = block(GotModBlocks.MOSSY_RIVERLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_BRICK_STAIRS = block(GotModBlocks.MOSSY_RIVERLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_BRICK_WALL = block(GotModBlocks.MOSSY_RIVERLANDS_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_BRICK_BUTTON = block(GotModBlocks.MOSSY_RIVERLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_RIVERLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> RIVERLANDS_COBBLESTONE_SLAB = block(GotModBlocks.RIVERLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> RIVERLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.RIVERLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> RIVERLANDS_COBBLESTONE_WALL = block(GotModBlocks.RIVERLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> RIVERLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.RIVERLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> RIVERLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.RIVERLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_RIVERLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_RIVERLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_RIVERLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_RIVERLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_RIVERLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_RIVERLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_RIVERLANDS_ROCK_SLAB = block(GotModBlocks.POLISHED_RIVERLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_RIVERLANDS_ROCK_STAIRS = block(GotModBlocks.POLISHED_RIVERLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_RIVERLANDS_ROCK_WALL = block(GotModBlocks.POLISHED_RIVERLANDS_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_RIVERLANDS_ROCK_BUTTON = block(GotModBlocks.POLISHED_RIVERLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_RIVERLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_RIVERLANDS_ROCK_PRESSURE_PLATE);

    // ── Stormlands ─────────────────────────────────────────
    public static final DeferredItem<Item> STORMLANDS_ROCK_SLAB = block(GotModBlocks.STORMLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> STORMLANDS_ROCK_STAIRS = block(GotModBlocks.STORMLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> STORMLANDS_ROCK_WALL = block(GotModBlocks.STORMLANDS_ROCK_WALL);
    public static final DeferredItem<Item> STORMLANDS_ROCK_BUTTON = block(GotModBlocks.STORMLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> STORMLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.STORMLANDS_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> STORMLANDS_BRICK_SLAB = block(GotModBlocks.STORMLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> STORMLANDS_BRICK_STAIRS = block(GotModBlocks.STORMLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> STORMLANDS_BRICK_WALL = block(GotModBlocks.STORMLANDS_BRICK_WALL);
    public static final DeferredItem<Item> STORMLANDS_BRICK_BUTTON = block(GotModBlocks.STORMLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> STORMLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.STORMLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_STORMLANDS_BRICK_SLAB = block(GotModBlocks.CRACKED_STORMLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_STORMLANDS_BRICK_STAIRS = block(GotModBlocks.CRACKED_STORMLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_STORMLANDS_BRICK_WALL = block(GotModBlocks.CRACKED_STORMLANDS_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_STORMLANDS_BRICK_BUTTON = block(GotModBlocks.CRACKED_STORMLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_STORMLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_STORMLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_BRICK_SLAB = block(GotModBlocks.MOSSY_STORMLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_BRICK_STAIRS = block(GotModBlocks.MOSSY_STORMLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_BRICK_WALL = block(GotModBlocks.MOSSY_STORMLANDS_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_BRICK_BUTTON = block(GotModBlocks.MOSSY_STORMLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_STORMLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> STORMLANDS_COBBLESTONE_SLAB = block(GotModBlocks.STORMLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> STORMLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.STORMLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> STORMLANDS_COBBLESTONE_WALL = block(GotModBlocks.STORMLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> STORMLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.STORMLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> STORMLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.STORMLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_STORMLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_STORMLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_STORMLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_STORMLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_STORMLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_STORMLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_STORMLANDS_ROCK_SLAB = block(GotModBlocks.POLISHED_STORMLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_STORMLANDS_ROCK_STAIRS = block(GotModBlocks.POLISHED_STORMLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_STORMLANDS_ROCK_WALL = block(GotModBlocks.POLISHED_STORMLANDS_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_STORMLANDS_ROCK_BUTTON = block(GotModBlocks.POLISHED_STORMLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_STORMLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_STORMLANDS_ROCK_PRESSURE_PLATE);

    // ── Vale ─────────────────────────────────────────
    public static final DeferredItem<Item> VALE_ROCK_SLAB = block(GotModBlocks.VALE_ROCK_SLAB);
    public static final DeferredItem<Item> VALE_ROCK_STAIRS = block(GotModBlocks.VALE_ROCK_STAIRS);
    public static final DeferredItem<Item> VALE_ROCK_WALL = block(GotModBlocks.VALE_ROCK_WALL);
    public static final DeferredItem<Item> VALE_ROCK_BUTTON = block(GotModBlocks.VALE_ROCK_BUTTON);
    public static final DeferredItem<Item> VALE_ROCK_PRESSURE_PLATE = block(GotModBlocks.VALE_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> VALE_BRICK_SLAB = block(GotModBlocks.VALE_BRICK_SLAB);
    public static final DeferredItem<Item> VALE_BRICK_STAIRS = block(GotModBlocks.VALE_BRICK_STAIRS);
    public static final DeferredItem<Item> VALE_BRICK_WALL = block(GotModBlocks.VALE_BRICK_WALL);
    public static final DeferredItem<Item> VALE_BRICK_BUTTON = block(GotModBlocks.VALE_BRICK_BUTTON);
    public static final DeferredItem<Item> VALE_BRICK_PRESSURE_PLATE = block(GotModBlocks.VALE_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_VALE_BRICK_SLAB = block(GotModBlocks.CRACKED_VALE_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_VALE_BRICK_STAIRS = block(GotModBlocks.CRACKED_VALE_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_VALE_BRICK_WALL = block(GotModBlocks.CRACKED_VALE_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_VALE_BRICK_BUTTON = block(GotModBlocks.CRACKED_VALE_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_VALE_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_VALE_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_VALE_BRICK_SLAB = block(GotModBlocks.MOSSY_VALE_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_VALE_BRICK_STAIRS = block(GotModBlocks.MOSSY_VALE_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_VALE_BRICK_WALL = block(GotModBlocks.MOSSY_VALE_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_VALE_BRICK_BUTTON = block(GotModBlocks.MOSSY_VALE_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_VALE_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_VALE_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> VALE_COBBLESTONE_SLAB = block(GotModBlocks.VALE_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> VALE_COBBLESTONE_STAIRS = block(GotModBlocks.VALE_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> VALE_COBBLESTONE_WALL = block(GotModBlocks.VALE_COBBLESTONE_WALL);
    public static final DeferredItem<Item> VALE_COBBLESTONE_BUTTON = block(GotModBlocks.VALE_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> VALE_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.VALE_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_VALE_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_VALE_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_VALE_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_VALE_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_VALE_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_VALE_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_VALE_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_VALE_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_VALE_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_VALE_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_VALE_ROCK_SLAB = block(GotModBlocks.POLISHED_VALE_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_VALE_ROCK_STAIRS = block(GotModBlocks.POLISHED_VALE_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_VALE_ROCK_WALL = block(GotModBlocks.POLISHED_VALE_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_VALE_ROCK_BUTTON = block(GotModBlocks.POLISHED_VALE_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_VALE_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_VALE_ROCK_PRESSURE_PLATE);

    // ── Westerlands ─────────────────────────────────────────
    public static final DeferredItem<Item> WESTERLANDS_ROCK_SLAB = block(GotModBlocks.WESTERLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> WESTERLANDS_ROCK_STAIRS = block(GotModBlocks.WESTERLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> WESTERLANDS_ROCK_WALL = block(GotModBlocks.WESTERLANDS_ROCK_WALL);
    public static final DeferredItem<Item> WESTERLANDS_ROCK_BUTTON = block(GotModBlocks.WESTERLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> WESTERLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.WESTERLANDS_ROCK_PRESSURE_PLATE);
    public static final DeferredItem<Item> WESTERLANDS_BRICK_SLAB = block(GotModBlocks.WESTERLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> WESTERLANDS_BRICK_STAIRS = block(GotModBlocks.WESTERLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> WESTERLANDS_BRICK_WALL = block(GotModBlocks.WESTERLANDS_BRICK_WALL);
    public static final DeferredItem<Item> WESTERLANDS_BRICK_BUTTON = block(GotModBlocks.WESTERLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> WESTERLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.WESTERLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> CRACKED_WESTERLANDS_BRICK_SLAB = block(GotModBlocks.CRACKED_WESTERLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> CRACKED_WESTERLANDS_BRICK_STAIRS = block(GotModBlocks.CRACKED_WESTERLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> CRACKED_WESTERLANDS_BRICK_WALL = block(GotModBlocks.CRACKED_WESTERLANDS_BRICK_WALL);
    public static final DeferredItem<Item> CRACKED_WESTERLANDS_BRICK_BUTTON = block(GotModBlocks.CRACKED_WESTERLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> CRACKED_WESTERLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.CRACKED_WESTERLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_BRICK_SLAB = block(GotModBlocks.MOSSY_WESTERLANDS_BRICK_SLAB);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_BRICK_STAIRS = block(GotModBlocks.MOSSY_WESTERLANDS_BRICK_STAIRS);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_BRICK_WALL = block(GotModBlocks.MOSSY_WESTERLANDS_BRICK_WALL);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_BRICK_BUTTON = block(GotModBlocks.MOSSY_WESTERLANDS_BRICK_BUTTON);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_BRICK_PRESSURE_PLATE = block(GotModBlocks.MOSSY_WESTERLANDS_BRICK_PRESSURE_PLATE);
    public static final DeferredItem<Item> WESTERLANDS_COBBLESTONE_SLAB = block(GotModBlocks.WESTERLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> WESTERLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.WESTERLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> WESTERLANDS_COBBLESTONE_WALL = block(GotModBlocks.WESTERLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> WESTERLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.WESTERLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> WESTERLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.WESTERLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_COBBLESTONE_SLAB = block(GotModBlocks.MOSSY_WESTERLANDS_COBBLESTONE_SLAB);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_COBBLESTONE_STAIRS = block(GotModBlocks.MOSSY_WESTERLANDS_COBBLESTONE_STAIRS);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_COBBLESTONE_WALL = block(GotModBlocks.MOSSY_WESTERLANDS_COBBLESTONE_WALL);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_COBBLESTONE_BUTTON = block(GotModBlocks.MOSSY_WESTERLANDS_COBBLESTONE_BUTTON);
    public static final DeferredItem<Item> MOSSY_WESTERLANDS_COBBLESTONE_PRESSURE_PLATE = block(GotModBlocks.MOSSY_WESTERLANDS_COBBLESTONE_PRESSURE_PLATE);
    public static final DeferredItem<Item> POLISHED_WESTERLANDS_ROCK_SLAB = block(GotModBlocks.POLISHED_WESTERLANDS_ROCK_SLAB);
    public static final DeferredItem<Item> POLISHED_WESTERLANDS_ROCK_STAIRS = block(GotModBlocks.POLISHED_WESTERLANDS_ROCK_STAIRS);
    public static final DeferredItem<Item> POLISHED_WESTERLANDS_ROCK_WALL = block(GotModBlocks.POLISHED_WESTERLANDS_ROCK_WALL);
    public static final DeferredItem<Item> POLISHED_WESTERLANDS_ROCK_BUTTON = block(GotModBlocks.POLISHED_WESTERLANDS_ROCK_BUTTON);
    public static final DeferredItem<Item> POLISHED_WESTERLANDS_ROCK_PRESSURE_PLATE = block(GotModBlocks.POLISHED_WESTERLANDS_ROCK_PRESSURE_PLATE);


    private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
        return REGISTRY.registerItem(name, supplier, new Item.Properties());
    }

    private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
        return block(block, new Item.Properties());
    }

    private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
        return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
    }
}