package net.got.init;

import net.got.block.*;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.Block;

import net.got.GotMod;

import java.util.function.Function;

public class GotModBlocks {
    public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(GotMod.MODID);
    public static final DeferredBlock<Block> WEIRWOOD_LOG = register("weirwood_log", WeirwoodLogBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_WOOD = register("weirwood_wood", WeirwoodWoodBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_PLANKS = register("weirwood_planks", WeirwoodPlanksBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_LEAVES = register("weirwood_leaves", WeirwoodLeavesBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_STAIRS = register("weirwood_stairs", WeirwoodStairsBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_SLAB = register("weirwood_slab", WeirwoodSlabBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_FENCE = register("weirwood_fence", WeirwoodFenceBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_FENCE_GATE = register("weirwood_fence_gate", WeirwoodFenceGateBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_PRESSURE_PLATE = register("weirwood_pressure_plate", WeirwoodPressurePlateBlock::new);
    public static final DeferredBlock<Block> WEIRWOOD_BUTTON = register("weirwood_button", WeirwoodButtonBlock::new);
    public static final DeferredBlock<Block> ASPEN_LOG = register("aspen_log", AspenLogBlock::new);
    public static final DeferredBlock<Block> ASPEN_WOOD = register("aspen_wood", AspenWoodBlock::new);
    public static final DeferredBlock<Block> ASPEN_PLANKS = register("aspen_planks", AspenPlanksBlock::new);
    public static final DeferredBlock<Block> ASPEN_LEAVES = register("aspen_leaves", AspenLeavesBlock::new);
    public static final DeferredBlock<Block> ASPEN_STAIRS = register("aspen_stairs", AspenStairsBlock::new);
    public static final DeferredBlock<Block> ASPEN_SLAB = register("aspen_slab", AspenSlabBlock::new);
    public static final DeferredBlock<Block> ASPEN_FENCE = register("aspen_fence", AspenFenceBlock::new);
    public static final DeferredBlock<Block> ASPEN_FENCE_GATE = register("aspen_fence_gate", AspenFenceGateBlock::new);
    public static final DeferredBlock<Block> ASPEN_PRESSURE_PLATE = register("aspen_pressure_plate", AspenPressurePlateBlock::new);
    public static final DeferredBlock<Block> ASPEN_BUTTON = register("aspen_button", AspenButtonBlock::new);
    public static final DeferredBlock<Block> ALDER_LOG = register("alder_log", AlderLogBlock::new);
    public static final DeferredBlock<Block> ALDER_WOOD = register("alder_wood", AlderWoodBlock::new);
    public static final DeferredBlock<Block> ALDER_PLANKS = register("alder_planks", AlderPlanksBlock::new);
    public static final DeferredBlock<Block> ALDER_LEAVES = register("alder_leaves", AlderLeavesBlock::new);
    public static final DeferredBlock<Block> ALDER_STAIRS = register("alder_stairs", AlderStairsBlock::new);
    public static final DeferredBlock<Block> ALDER_SLAB = register("alder_slab", AlderSlabBlock::new);
    public static final DeferredBlock<Block> ALDER_FENCE = register("alder_fence", AlderFenceBlock::new);
    public static final DeferredBlock<Block> ALDER_FENCE_GATE = register("alder_fence_gate", AlderFenceGateBlock::new);
    public static final DeferredBlock<Block> ALDER_PRESSURE_PLATE = register("alder_pressure_plate", AlderPressurePlateBlock::new);
    public static final DeferredBlock<Block> ALDER_BUTTON = register("alder_button", AlderButtonBlock::new);
    public static final DeferredBlock<Block> PINE_LOG = register("pine_log", PineLogBlock::new);
	public static final DeferredBlock<Block> PINE_WOOD = register("pine_wood", PineWoodBlock::new);
	public static final DeferredBlock<Block> PINE_PLANKS = register("pine_planks", PinePlanksBlock::new);
	public static final DeferredBlock<Block> PINE_LEAVES = register("pine_leaves", PineLeavesBlock::new);
	public static final DeferredBlock<Block> PINE_STAIRS = register("pine_stairs", PineStairsBlock::new);
	public static final DeferredBlock<Block> PINE_SLAB = register("pine_slab", PineSlabBlock::new);
	public static final DeferredBlock<Block> PINE_FENCE = register("pine_fence", PineFenceBlock::new);
	public static final DeferredBlock<Block> PINE_FENCE_GATE = register("pine_fence_gate", PineFenceGateBlock::new);
	public static final DeferredBlock<Block> PINE_PRESSURE_PLATE = register("pine_pressure_plate", PinePressurePlateBlock::new);
	public static final DeferredBlock<Block> PINE_BUTTON = register("pine_button", PineButtonBlock::new);
	public static final DeferredBlock<Block> FIR_LOG = register("fir_log", FirLogBlock::new);
	public static final DeferredBlock<Block> FIR_WOOD = register("fir_wood", FirWoodBlock::new);
	public static final DeferredBlock<Block> FIR_PLANKS = register("fir_planks", FirPlanksBlock::new);
	public static final DeferredBlock<Block> FIR_LEAVES = register("fir_leaves", FirLeavesBlock::new);
	public static final DeferredBlock<Block> FIR_STAIRS = register("fir_stairs", FirStairsBlock::new);
	public static final DeferredBlock<Block> FIR_SLAB = register("fir_slab", FirSlabBlock::new);
	public static final DeferredBlock<Block> FIR_FENCE = register("fir_fence", FirFenceBlock::new);
	public static final DeferredBlock<Block> FIR_FENCE_GATE = register("fir_fence_gate", FirFenceGateBlock::new);
	public static final DeferredBlock<Block> FIR_PRESSURE_PLATE = register("fir_pressure_plate", FirPressurePlateBlock::new);
	public static final DeferredBlock<Block> FIR_BUTTON = register("fir_button", FirButtonBlock::new);
	public static final DeferredBlock<Block> SENTINAL_LOG = register("sentinal_log", SentinalLogBlock::new);
	public static final DeferredBlock<Block> SENTINAL_WOOD = register("sentinal_wood", SentinalWoodBlock::new);
	public static final DeferredBlock<Block> SENTINAL_PLANKS = register("sentinal_planks", SentinalPlanksBlock::new);
	public static final DeferredBlock<Block> SENTINAL_LEAVES = register("sentinal_leaves", SentinalLeavesBlock::new);
	public static final DeferredBlock<Block> SENTINAL_STAIRS = register("sentinal_stairs", SentinalStairsBlock::new);
	public static final DeferredBlock<Block> SENTINAL_SLAB = register("sentinal_slab", SentinalSlabBlock::new);
	public static final DeferredBlock<Block> SENTINAL_FENCE = register("sentinal_fence", SentinalFenceBlock::new);
	public static final DeferredBlock<Block> SENTINAL_FENCE_GATE = register("sentinal_fence_gate", SentinalFenceGateBlock::new);
	public static final DeferredBlock<Block> SENTINAL_PRESSURE_PLATE = register("sentinal_pressure_plate", SentinalPressurePlateBlock::new);
	public static final DeferredBlock<Block> SENTINAL_BUTTON = register("sentinal_button", SentinalButtonBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_LOG = register("ironwood_log", IronwoodLogBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_WOOD = register("ironwood_wood", IronwoodWoodBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_PLANKS = register("ironwood_planks", IronwoodPlanksBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_LEAVES = register("ironwood_leaves", IronwoodLeavesBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_STAIRS = register("ironwood_stairs", IronwoodStairsBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_SLAB = register("ironwood_slab", IronwoodSlabBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_FENCE = register("ironwood_fence", IronwoodFenceBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_FENCE_GATE = register("ironwood_fence_gate", IronwoodFenceGateBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_PRESSURE_PLATE = register("ironwood_pressure_plate", IronwoodPressurePlateBlock::new);
	public static final DeferredBlock<Block> IRONWOOD_BUTTON = register("ironwood_button", IronwoodButtonBlock::new);
	public static final DeferredBlock<Block> BEECH_LOG = register("beech_log", BeechLogBlock::new);
	public static final DeferredBlock<Block> BEECH_WOOD = register("beech_wood", BeechWoodBlock::new);
	public static final DeferredBlock<Block> BEECH_PLANKS = register("beech_planks", BeechPlanksBlock::new);
	public static final DeferredBlock<Block> BEECH_LEAVES = register("beech_leaves", BeechLeavesBlock::new);
	public static final DeferredBlock<Block> BEECH_STAIRS = register("beech_stairs", BeechStairsBlock::new);
	public static final DeferredBlock<Block> BEECH_SLAB = register("beech_slab", BeechSlabBlock::new);
	public static final DeferredBlock<Block> BEECH_FENCE = register("beech_fence", BeechFenceBlock::new);
	public static final DeferredBlock<Block> BEECH_FENCE_GATE = register("beech_fence_gate", BeechFenceGateBlock::new);
	public static final DeferredBlock<Block> BEECH_PRESSURE_PLATE = register("beech_pressure_plate", BeechPressurePlateBlock::new);
	public static final DeferredBlock<Block> BEECH_BUTTON = register("beech_button", BeechButtonBlock::new);
	public static final DeferredBlock<Block> NORTH_ROCK = register("north_rock", NorthRockBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_LOG = register("soldier_pine_log", SoldierPineLogBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_WOOD = register("soldier_pine_wood", SoldierPineWoodBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_PLANKS = register("soldier_pine_planks", SoldierPinePlanksBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_LEAVES = register("soldier_pine_leaves", SoldierPineLeavesBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_STAIRS = register("soldier_pine_stairs", SoldierPineStairsBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_SLAB = register("soldier_pine_slab", SoldierPineSlabBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_FENCE = register("soldier_pine_fence", SoldierPineFenceBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_FENCE_GATE = register("soldier_pine_fence_gate", SoldierPineFenceGateBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_PRESSURE_PLATE = register("soldier_pine_pressure_plate", SoldierPinePressurePlateBlock::new);
	public static final DeferredBlock<Block> SOLDIER_PINE_BUTTON = register("soldier_pine_button", SoldierPineButtonBlock::new);
    public static final DeferredBlock<Block> ASH_LOG = register("ash_log", AshLogBlock::new);
    public static final DeferredBlock<Block> ASH_WOOD = register("ash_wood", AshWoodBlock::new);
    public static final DeferredBlock<Block> ASH_PLANKS = register("ash_planks", AshPlanksBlock::new);
    public static final DeferredBlock<Block> ASH_LEAVES = register("ash_leaves", AshLeavesBlock::new);
    public static final DeferredBlock<Block> ASH_STAIRS = register("ash_stairs", AshStairsBlock::new);
    public static final DeferredBlock<Block> ASH_SLAB = register("ash_slab", AshSlabBlock::new);
    public static final DeferredBlock<Block> ASH_FENCE = register("ash_fence", AshFenceBlock::new);
    public static final DeferredBlock<Block> ASH_FENCE_GATE = register("ash_fence_gate", AshFenceGateBlock::new);
    public static final DeferredBlock<Block> ASH_PRESSURE_PLATE = register("ash_pressure_plate", AshPressurePlateBlock::new);
    public static final DeferredBlock<Block> ASH_BUTTON = register("ash_button", AshButtonBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_LOG = register("hawthorn_log", HawthornLogBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_WOOD = register("hawthorn_wood", HawthornWoodBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_PLANKS = register("hawthorn_planks", HawthornPlanksBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_LEAVES = register("hawthorn_leaves", HawthornLeavesBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_STAIRS = register("hawthorn_stairs", HawthornStairsBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_SLAB = register("hawthorn_slab", HawthornSlabBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_FENCE = register("hawthorn_fence", HawthornFenceBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_FENCE_GATE = register("hawthorn_fence_gate", HawthornFenceGateBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_PRESSURE_PLATE = register("hawthorn_pressure_plate", HawthornPressurePlateBlock::new);
    public static final DeferredBlock<Block> HAWTHORN_BUTTON = register("hawthorn_button", HawthornButtonBlock::new);
    private static <B extends Block> DeferredBlock<B> register(String name, Function<BlockBehaviour.Properties, ? extends B> supplier) {
        return REGISTRY.registerBlock(name, supplier, BlockBehaviour.Properties.of());
    }
}